// ============================================================
// languages.js - نظام الترجمة المتعدد اللغات
// ============================================================

const translations = {
    // ===== اللغة العربية (AR) =====
    ar: {
        // عام
        'app_name': 'ZI Store',
        'welcome_back': '👋 مرحباً بعودتك',
        'login_subtitle': 'سجل الدخول للوصول إلى منتجاتك',
        'login_with_google': 'تسجيل الدخول عبر Google',
        'or': 'أو',
        'email': 'البريد الإلكتروني',
        'password': 'كلمة المرور',
        'forgot_password': 'نسيت كلمة المرور؟',
        'login': 'تسجيل الدخول',
        'no_account': 'ليس لديك حساب؟',
        'sign_up': 'إنشاء حساب',
        'create_account': '✨ إنشاء حساب',
        'register_subtitle': 'انضم إلى ZI Store اليوم',
        'full_name': 'الاسم الكامل',
        'confirm_password': 'تأكيد كلمة المرور',
        'country': 'الدولة',
        'language': 'اللغة',
        'referral_code': 'رمز الإحالة',
        'agree_terms': 'أوافق على الشروط والأحكام',
        'already_have_account': 'لديك حساب بالفعل؟',
        
        // الهيدر
        'search_products': '🔍 ابحث عن المنتجات...',
        'notifications': 'الإشعارات',
        'wishlist': 'المفضلة',
        'cart': 'السلة',
        'profile': 'الملف الشخصي',
        'logout': 'تسجيل الخروج',
        'admin_panel': 'لوحة الإدارة',
        
        // المنتجات
        'all_scripts': 'جميع السكربتات',
        'all': 'الكل',
        'free': 'مجاني',
        'vip': 'VIP',
        'browse': 'تصفح',
        'recommended': 'موصى لك',
        'no_products': 'لا توجد منتجات',
        'no_results': 'لا توجد نتائج',
        'total': 'الإجمالي',
        'favorites': 'المفضلة',
        'instant': 'فوري',
        'secure': 'آمن',
        'support': 'الدعم 24/7',
        'unavailable': 'غير متوفر',
        'coming_soon': 'قريباً',
        'add_to_cart': 'أضف إلى السلة',
        'download': 'تحميل',
        'details': 'تفاصيل',
        'share': 'مشاركة',
        'features': 'المميزات',
        'verified': '✅ منتج موثوق 100%',
        'price': 'السعر',
        'original_price': 'السعر الأصلي',
        
        // السلة
        'cart_empty': 'السلة فارغة',
        'start_shopping': 'ابدأ التسوق لإضافة منتجات',
        'subtotal': 'المجموع الفرعي',
        'total': 'المجموع الكلي',
        'checkout': 'إتمام الشراء',
        'clear_cart': 'تفريغ السلة',
        'view_cart': 'عرض السلة',
        'rp_points': 'نقاط الولاء',
        'use_rp': 'استخدام النقاط',
        'promo_code': 'رمز الخصم',
        'apply': 'تطبيق',
        'discount': 'خصم',
        
        // الدفع
        'payment': 'الدفع',
        'payment_method': 'طريقة الدفع',
        'litecoin': 'لايتكوين',
        'usdt': 'USDT',
        'telegram': 'تيليجرام',
        'binance': 'Binance',
        'exchange_rate': 'سعر الصرف',
        'continue': 'متابعة',
        'confirm_payment': 'تأكيد الدفع',
        'back': 'رجوع',
        'amount': 'المبلغ',
        'copy_address': 'نسخ العنوان',
        'transaction_hash': 'رابط المعاملة',
        'paste_hash': 'الصق رابط المعاملة...',
        'contact_telegram': 'تواصل عبر تيليجرام',
        
        // الملف الشخصي
        'edit_profile': 'تعديل الملف الشخصي',
        'name': 'الاسم',
        'telegram_username': 'اسم المستخدم في تيليجرام',
        'country_label': 'الدولة',
        'language_label': 'اللغة',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'password_security': 'كلمة المرور والأمان',
        'current_password': 'كلمة المرور الحالية',
        'new_password': 'كلمة المرور الجديدة',
        'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
        'change_password': 'تغيير كلمة المرور',
        'send_reset_link': 'إرسال رابط إعادة التعيين',
        'telegram_notifications': 'إشعارات تيليجرام',
        'status': 'الحالة',
        'linked': '✅ مرتبط',
        'unlinked': '❌ غير مرتبط',
        'bind_chat_id': 'معرف الدردشة المرتبط',
        'bot': 'البوت',
        'link_bot': 'ربط البوت',
        'test': 'اختبار',
        'check': 'تحقق',
        'unlink': 'إلغاء الربط',
        'connected_to': 'متصل بـ',
        'start_bot': 'ابدأ البوت',
        
        // الطلبات
        'order_history': 'سجل الطلبات',
        'no_orders': 'لا توجد طلبات',
        'pending': 'قيد الانتظار',
        'confirmed': 'مؤكد',
        'rejected': 'مرفوض',
        'order_id': 'رقم الطلب',
        'order_date': 'تاريخ الطلب',
        'items': 'المنتجات',
        'actions': 'الإجراءات',
        'delete': 'حذف',
        'clear_history': 'مسح السجل',
        
        // الإشعارات
        'notifications_title': 'الإشعارات',
        'mark_all_read': 'تحديد الكل كمقروء',
        'clear_all': 'مسح الكل',
        'no_notifications': 'لا توجد إشعارات',
        'new': 'جديد',
        
        // الترخيص
        'activate_script': 'تفعيل السكربت',
        'enter_licence': 'أدخل رمز الترخيص',
        'activate': 'تفعيل',
        'my_licences': 'تراخيصي',
        'no_licences': 'لا توجد تراخيص نشطة',
        'expired': 'منتهي الصلاحية',
        'active_until': 'نشط حتى',
        'copy_code': 'نسخ الكود',
        
        // الطلبات المخصصة
        'my_requests': 'طلباتي',
        'new_request': 'طلب جديد',
        'game_name': 'اسم اللعبة',
        'play_store_link': 'رابط متجر اللعب',
        'features_needed': 'المميزات المطلوبة',
        'budget': 'الميزانية',
        'submit_request': 'إرسال الطلب',
        
        // الإحالات
        'refer_earn': 'أحصل على مكافآت',
        'referral_code_label': 'رمز الإحالة الخاص بك',
        'referrals': 'الإحالات',
        'earned': 'المكتسب',
        'referral_activity': 'نشاط الإحالات',
        'no_referrals': 'لا توجد إحالات حتى الآن',
        'share_code': 'شارك رابطك لبدء الربح',
        'steps': 'الخطوات',
        'step1': 'شارك رمز الإحالة الخاص بك',
        'step2': 'يقومون بإنشاء حساب باستخدام رمزك',
        'step3': 'اربح مكافآت (10% من قيمة أول طلب لهم)',
        'joined': 'انضم',
        
        // الأدمن
        'dashboard': 'لوحة التحكم',
        'orders': 'الطلبات',
        'products': 'المنتجات',
        'users': 'المستخدمين',
        'downloads': 'التحميلات',
        'statistics': 'الإحصائيات',
        'logs': 'السجلات',
        'slider': 'السلايدر',
        'licences': 'التراخيص',
        'marquee': 'النص المتحرك',
        'payments': 'المدفوعات',
        'total_orders': 'إجمالي الطلبات',
        'total_revenue': 'إجمالي الإيرادات',
        'net_revenue': 'صافي الإيرادات (10%)',
        'refresh': 'تحديث',
        'add_product': 'إضافة منتج',
        'manage_featured': 'إدارة المميزات',
        'add_download': 'إضافة تحميل',
        'send_notification': 'إرسال إشعار',
        'add_slide': 'إضافة شريحة',
        'create_licence': 'إنشاء ترخيص',
        'slider_settings': 'إعدادات السلايدر',
        'enable_slider': 'تفعيل السلايدر',
        'disabled': 'معطل',
        'rotation_interval': 'فاصل التناوب (ثانية)',
        'save_settings': 'حفظ الإعدادات',
        
        // الرسائل العامة
        'loading': 'جاري التحميل...',
        'success': 'نجاح',
        'error': 'خطأ',
        'warning': 'تحذير',
        'info': 'معلومات',
        'close': 'إغلاق',
        'search': 'بحث',
        'edit': 'تعديل',
        'view': 'عرض',
        'ban': 'حظر',
        'unban': 'إلغاء الحظر',
        'delete_account': 'حذف الحساب',
        'confirm': 'تأكيد',
        'cancel_action': 'إلغاء',
        'yes': 'نعم',
        'no': 'لا',
        'ok': 'حسناً',
        'back_to_home': 'العودة للرئيسية',
        'see_all': 'عرض الكل',
        'load_more': 'تحميل المزيد',
        
        // السلايدر
        'slide_image': 'صورة الشريحة',
        'slide_title': 'العنوان (اختياري)',
        'slide_subtitle': 'العنوان الفرعي (اختياري)',
        'button_text': 'نص الزر',
        'button_link_type': 'نوع رابط الزر',
        'select_product': 'اختر منتجاً',
        'download_url': 'رابط التحميل',
        'custom_url': 'رابط مخصص',
        'none': 'لا شيء (بدون زر)',
        'add_slide_title': 'إضافة شريحة جديدة',
        'edit_slide_title': 'تعديل الشريحة',
        'save_changes': 'حفظ التعديلات',
        'slide_added': 'تم إضافة الشريحة بنجاح!',
        'slide_updated': 'تم تحديث الشريحة بنجاح!',
        'slide_deleted': 'تم حذف الشريحة',
        'no_slides': 'لا توجد شرائح. اضغط "إضافة شريحة" للبدء.',
        
        // الماركي
        'marquee_settings': 'إعدادات النص المتحرك',
        'enable_marquee': 'تفعيل النص المتحرك',
        'marquee_text': 'نص الماركي (افصل العناصر بـ | )',
        'marquee_saved': 'تم حفظ إعدادات الماركي!',
        
        // المودالات
        'user_menu': 'القائمة',
        'requests': 'الطلبات',
        'referrals_title': 'الإحالات',
        'reset_password': 'إعادة تعيين كلمة المرور',
        'send_link': 'إرسال الرابط',
        'search_placeholder': 'ابحث عن المنتجات...',
        'no_matching': 'لا توجد نتائج مطابقة',
        
        // أيقونات البلدان
        'country_tunisia': '🇹🇳 تونس',
        'country_algeria': '🇩🇿 الجزائر',
        'country_morocco': '🇲🇦 المغرب',
        'country_egypt': '🇪🇬 مصر',
        'country_saudi': '🇸🇦 السعودية',
        'country_uae': '🇦🇪 الإمارات',
        'country_other': '🌍 أخرى',
        
        // اللغات
        'lang_english': '🇬🇧 English',
        'lang_arabic': '🇸🇦 العربية',
        'lang_french': '🇫🇷 Français',
        'lang_italian': '🇮🇹 Italiano',
        'lang_german': '🇩🇪 Deutsch',
        'lang_spanish': '🇪🇸 Español',
        'lang_portuguese': '🇵🇹 Português'
    },
    
    // ===== اللغة الإنجليزية (EN) =====
    en: {
        'app_name': 'ZI Store',
        'welcome_back': '👋 Welcome Back',
        'login_subtitle': 'Login to access your scripts',
        'login_with_google': 'Login with Google',
        'or': 'or',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Forgot password?',
        'login': 'Login',
        'no_account': "Don't have an account?",
        'sign_up': 'Sign up',
        'create_account': '✨ Create Account',
        'register_subtitle': 'Join ZI Store today',
        'full_name': 'Full Name',
        'confirm_password': 'Confirm Password',
        'country': 'Country',
        'language': 'Language',
        'referral_code': 'Referral Code',
        'agree_terms': 'I agree to the Terms & Conditions',
        'already_have_account': 'Already have an account?',
        'search_products': '🔍 Search products...',
        'notifications': 'Notifications',
        'wishlist': 'Wishlist',
        'cart': 'Cart',
        'profile': 'Profile',
        'logout': 'Logout',
        'admin_panel': 'Admin Panel',
        'all_scripts': 'All Scripts',
        'all': 'All',
        'free': 'Free',
        'vip': 'VIP',
        'browse': 'Browse',
        'recommended': 'Recommended for You',
        'no_products': 'No products',
        'no_results': 'No results',
        'total': 'Total',
        'favorites': 'Favorites',
        'instant': 'Instant',
        'secure': 'Secure',
        'support': '24/7 Support',
        'unavailable': 'Unavailable',
        'coming_soon': 'Coming soon',
        'add_to_cart': 'Add to Cart',
        'download': 'Download',
        'details': 'Details',
        'share': 'Share',
        'features': 'Features',
        'verified': '✅ 100% VERIFIED WORKING PRODUCT',
        'price': 'Price',
        'original_price': 'Original Price',
        'cart_empty': 'Cart is empty',
        'start_shopping': 'Start shopping to add items',
        'subtotal': 'Subtotal',
        'total': 'Total',
        'checkout': 'Checkout',
        'clear_cart': 'Clear Cart',
        'view_cart': 'View Cart',
        'rp_points': 'Loyalty Points',
        'use_rp': 'Use RP',
        'promo_code': 'Promo Code',
        'apply': 'Apply',
        'discount': 'Discount',
        'payment': 'Payment',
        'payment_method': 'Payment Method',
        'litecoin': 'Litecoin',
        'usdt': 'USDT',
        'telegram': 'Telegram',
        'binance': 'Binance',
        'exchange_rate': 'Exchange Rate',
        'continue': 'Continue',
        'confirm_payment': 'Confirm Payment',
        'back': 'Back',
        'amount': 'Amount',
        'copy_address': 'Copy Address',
        'transaction_hash': 'Transaction Hash',
        'paste_hash': 'Paste transaction hash...',
        'contact_telegram': 'Contact via Telegram',
        'edit_profile': 'Edit Profile',
        'name': 'Name',
        'telegram_username': 'Telegram Username',
        'country_label': 'Country',
        'language_label': 'Language',
        'save': 'Save',
        'cancel': 'Cancel',
        'password_security': 'Password & Security',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_new_password': 'Confirm New Password',
        'change_password': 'Change Password',
        'send_reset_link': 'Send Reset Link',
        'telegram_notifications': 'Telegram Notifications',
        'status': 'Status',
        'linked': '✅ Linked',
        'unlinked': '❌ Unlinked',
        'bind_chat_id': 'Bound Chat ID',
        'bot': 'Bot',
        'link_bot': 'Link Bot',
        'test': 'Test',
        'check': 'Check',
        'unlink': 'Unlink',
        'connected_to': 'Connected to',
        'start_bot': 'Start bot',
        'order_history': 'Order History',
        'no_orders': 'No orders yet',
        'pending': 'Pending',
        'confirmed': 'Confirmed',
        'rejected': 'Rejected',
        'order_id': 'Order ID',
        'order_date': 'Order Date',
        'items': 'Items',
        'actions': 'Actions',
        'delete': 'Delete',
        'clear_history': 'Clear History',
        'notifications_title': 'Notifications',
        'mark_all_read': 'Mark all read',
        'clear_all': 'Clear all',
        'no_notifications': 'No notifications',
        'new': 'New',
        'activate_script': 'Activate Script',
        'enter_licence': 'Enter your licence code',
        'activate': 'Activate',
        'my_licences': 'My Licences',
        'no_licences': 'No active licences',
        'expired': 'Expired',
        'active_until': 'Active until',
        'copy_code': 'Copy code',
        'my_requests': 'My Requests',
        'new_request': 'New Request',
        'game_name': 'Game Name',
        'play_store_link': 'Play Store Link',
        'features_needed': 'Features Needed',
        'budget': 'Budget',
        'submit_request': 'Submit Request',
        'refer_earn': 'Refer & Earn',
        'referral_code_label': 'Your Referral Code',
        'referrals': 'Referrals',
        'earned': 'Earned',
        'referral_activity': 'Referral Activity',
        'no_referrals': 'No referrals yet',
        'share_code': 'Share your link to start earning',
        'steps': 'Steps',
        'step1': 'Share your referral code',
        'step2': 'They create an account using your code',
        'step3': 'Earn Rewards (10% of their first order)',
        'joined': 'Joined',
        'dashboard': 'Dashboard',
        'orders': 'Orders',
        'products': 'Products',
        'users': 'Users',
        'downloads': 'Downloads',
        'statistics': 'Statistics',
        'logs': 'Logs',
        'slider': 'Slider',
        'licences': 'Licences',
        'marquee': 'Marquee',
        'payments': 'Payments',
        'total_orders': 'Total Orders',
        'total_revenue': 'Total Revenue',
        'net_revenue': 'Net Revenue (10%)',
        'refresh': 'Refresh',
        'add_product': 'Add Product',
        'manage_featured': 'Manage Featured',
        'add_download': 'Add Download',
        'send_notification': 'Send Notification',
        'add_slide': 'Add Slide',
        'create_licence': 'Create Licence',
        'slider_settings': 'Slider Settings',
        'enable_slider': 'Enable Slider',
        'disabled': 'Disabled',
        'rotation_interval': 'Rotation Interval (seconds)',
        'save_settings': 'Save Settings',
        'loading': 'Loading...',
        'success': 'Success',
        'error': 'Error',
        'warning': 'Warning',
        'info': 'Info',
        'close': 'Close',
        'search': 'Search',
        'edit': 'Edit',
        'view': 'View',
        'ban': 'Ban',
        'unban': 'Unban',
        'delete_account': 'Delete Account',
        'confirm': 'Confirm',
        'cancel_action': 'Cancel',
        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'back_to_home': 'Back to Home',
        'see_all': 'See All',
        'load_more': 'Load More',
        'slide_image': 'Slide Image',
        'slide_title': 'Title (optional)',
        'slide_subtitle': 'Subtitle (optional)',
        'button_text': 'Button Text',
        'button_link_type': 'Button Link Type',
        'select_product': 'Select Product',
        'download_url': 'Download URL',
        'custom_url': 'Custom URL',
        'none': 'None (no button)',
        'add_slide_title': 'Add New Slide',
        'edit_slide_title': 'Edit Slide',
        'save_changes': 'Save Changes',
        'slide_added': 'Slide added successfully!',
        'slide_updated': 'Slide updated successfully!',
        'slide_deleted': 'Slide deleted',
        'no_slides': 'No slides yet. Click "Add Slide" to get started.',
        'marquee_settings': 'Marquee Settings',
        'enable_marquee': 'Enable Marquee',
        'marquee_text': 'Marquee Text (separate items with | )',
        'marquee_saved': 'Marquee settings saved!',
        'user_menu': 'Menu',
        'requests': 'Requests',
        'referrals_title': 'Referrals',
        'reset_password': 'Reset Password',
        'send_link': 'Send Link',
        'search_placeholder': 'Search products...',
        'no_matching': 'No matching results',
        'country_tunisia': '🇹🇳 Tunisia',
        'country_algeria': '🇩🇿 Algeria',
        'country_morocco': '🇲🇦 Morocco',
        'country_egypt': '🇪🇬 Egypt',
        'country_saudi': '🇸🇦 Saudi Arabia',
        'country_uae': '🇦🇪 UAE',
        'country_other': '🌍 Other',
        'lang_english': '🇬🇧 English',
        'lang_arabic': '🇸🇦 العربية',
        'lang_french': '🇫🇷 Français',
        'lang_italian': '🇮🇹 Italiano',
        'lang_german': '🇩🇪 Deutsch',
        'lang_spanish': '🇪🇸 Español',
        'lang_portuguese': '🇵🇹 Português'
    },
    
    // ===== اللغة الفرنسية (FR) =====
    fr: {
        'app_name': 'ZI Store',
        'welcome_back': '👋 Bon retour',
        'login_subtitle': 'Connectez-vous pour accéder à vos scripts',
        'login_with_google': 'Se connecter avec Google',
        'or': 'ou',
        'email': 'Email',
        'password': 'Mot de passe',
        'forgot_password': 'Mot de passe oublié ?',
        'login': 'Connexion',
        'no_account': "Vous n'avez pas de compte ?",
        'sign_up': "S'inscrire",
        'create_account': '✨ Créer un compte',
        'register_subtitle': "Rejoignez ZI Store aujourd'hui",
        'full_name': 'Nom complet',
        'confirm_password': 'Confirmer le mot de passe',
        'country': 'Pays',
        'language': 'Langue',
        'referral_code': 'Code de parrainage',
        'agree_terms': "J'accepte les conditions générales",
        'already_have_account': 'Vous avez déjà un compte ?',
        'search_products': '🔍 Rechercher des produits...',
        'notifications': 'Notifications',
        'wishlist': 'Favoris',
        'cart': 'Panier',
        'profile': 'Profil',
        'logout': 'Déconnexion',
        'admin_panel': "Panneau d'administration",
        'all_scripts': 'Tous les scripts',
        'all': 'Tous',
        'free': 'Gratuit',
        'vip': 'VIP',
        'browse': 'Parcourir',
        'recommended': 'Recommandé pour vous',
        'no_products': 'Aucun produit',
        'no_results': 'Aucun résultat',
        'total': 'Total',
        'favorites': 'Favoris',
        'instant': 'Instantané',
        'secure': 'Sécurisé',
        'support': 'Support 24/7',
        'unavailable': 'Indisponible',
        'coming_soon': 'Bientôt disponible',
        'add_to_cart': 'Ajouter au panier',
        'download': 'Télécharger',
        'details': 'Détails',
        'share': 'Partager',
        'features': 'Fonctionnalités',
        'verified': '✅ PRODUIT 100% VÉRIFIÉ',
        'price': 'Prix',
        'original_price': 'Prix original',
        'cart_empty': 'Le panier est vide',
        'start_shopping': 'Commencez à magasiner',
        'subtotal': 'Sous-total',
        'total': 'Total',
        'checkout': 'Paiement',
        'clear_cart': 'Vider le panier',
        'view_cart': 'Voir le panier',
        'rp_points': 'Points de fidélité',
        'use_rp': 'Utiliser RP',
        'promo_code': 'Code promo',
        'apply': 'Appliquer',
        'discount': 'Réduction',
        'payment': 'Paiement',
        'payment_method': 'Méthode de paiement',
        'litecoin': 'Litecoin',
        'usdt': 'USDT',
        'telegram': 'Telegram',
        'binance': 'Binance',
        'exchange_rate': 'Taux de change',
        'continue': 'Continuer',
        'confirm_payment': 'Confirmer le paiement',
        'back': 'Retour',
        'amount': 'Montant',
        'copy_address': 'Copier l\'adresse',
        'transaction_hash': 'Hash de transaction',
        'paste_hash': 'Collez le hash de transaction...',
        'contact_telegram': 'Contacter via Telegram',
        'edit_profile': 'Modifier le profil',
        'name': 'Nom',
        'telegram_username': "Nom d'utilisateur Telegram",
        'country_label': 'Pays',
        'language_label': 'Langue',
        'save': 'Enregistrer',
        'cancel': 'Annuler',
        'password_security': 'Mot de passe et sécurité',
        'current_password': 'Mot de passe actuel',
        'new_password': 'Nouveau mot de passe',
        'confirm_new_password': 'Confirmer le nouveau mot de passe',
        'change_password': 'Changer le mot de passe',
        'send_reset_link': 'Envoyer le lien de réinitialisation',
        'telegram_notifications': 'Notifications Telegram',
        'status': 'Statut',
        'linked': '✅ Lié',
        'unlinked': '❌ Non lié',
        'bind_chat_id': 'ID de chat lié',
        'bot': 'Bot',
        'link_bot': 'Lier le bot',
        'test': 'Tester',
        'check': 'Vérifier',
        'unlink': 'Délier',
        'connected_to': 'Connecté à',
        'start_bot': 'Démarrer le bot',
        'order_history': 'Historique des commandes',
        'no_orders': 'Aucune commande',
        'pending': 'En attente',
        'confirmed': 'Confirmée',
        'rejected': 'Rejetée',
        'order_id': 'ID de commande',
        'order_date': 'Date de commande',
        'items': 'Articles',
        'actions': 'Actions',
        'delete': 'Supprimer',
        'clear_history': 'Effacer l\'historique',
        'notifications_title': 'Notifications',
        'mark_all_read': 'Tout marquer comme lu',
        'clear_all': 'Tout effacer',
        'no_notifications': 'Aucune notification',
        'new': 'Nouveau',
        'activate_script': 'Activer le script',
        'enter_licence': 'Entrez votre code de licence',
        'activate': 'Activer',
        'my_licences': 'Mes licences',
        'no_licences': 'Aucune licence active',
        'expired': 'Expiré',
        'active_until': 'Actif jusqu\'au',
        'copy_code': 'Copier le code',
        'my_requests': 'Mes demandes',
        'new_request': 'Nouvelle demande',
        'game_name': 'Nom du jeu',
        'play_store_link': 'Lien Play Store',
        'features_needed': 'Fonctionnalités souhaitées',
        'budget': 'Budget',
        'submit_request': 'Envoyer la demande',
        'refer_earn': 'Parrainer et gagner',
        'referral_code_label': 'Votre code de parrainage',
        'referrals': 'Parrainages',
        'earned': 'Gagné',
        'referral_activity': 'Activité de parrainage',
        'no_referrals': 'Aucun parrainage encore',
        'share_code': 'Partagez votre lien pour commencer à gagner',
        'steps': 'Étapes',
        'step1': 'Partagez votre code de parrainage',
        'step2': 'Ils créent un compte avec votre code',
        'step3': 'Gagnez des récompenses (10% de leur première commande)',
        'joined': 'A rejoint',
        'dashboard': 'Tableau de bord',
        'orders': 'Commandes',
        'products': 'Produits',
        'users': 'Utilisateurs',
        'downloads': 'Téléchargements',
        'statistics': 'Statistiques',
        'logs': 'Journaux',
        'slider': 'Carrousel',
        'licences': 'Licences',
        'marquee': 'Marquee',
        'payments': 'Paiements',
        'total_orders': 'Total des commandes',
        'total_revenue': 'Revenu total',
        'net_revenue': 'Revenu net (10%)',
        'refresh': 'Actualiser',
        'add_product': 'Ajouter un produit',
        'manage_featured': 'Gérer les produits en vedette',
        'add_download': 'Ajouter un téléchargement',
        'send_notification': 'Envoyer une notification',
        'add_slide': 'Ajouter une diapositive',
        'create_licence': 'Créer une licence',
        'slider_settings': 'Paramètres du carrousel',
        'enable_slider': 'Activer le carrousel',
        'disabled': 'Désactivé',
        'rotation_interval': 'Intervalle de rotation (secondes)',
        'save_settings': 'Enregistrer les paramètres',
        'loading': 'Chargement...',
        'success': 'Succès',
        'error': 'Erreur',
        'warning': 'Attention',
        'info': 'Info',
        'close': 'Fermer',
        'search': 'Rechercher',
        'edit': 'Modifier',
        'view': 'Voir',
        'ban': 'Bannir',
        'unban': 'Débannir',
        'delete_account': 'Supprimer le compte',
        'confirm': 'Confirmer',
        'cancel_action': 'Annuler',
        'yes': 'Oui',
        'no': 'Non',
        'ok': 'OK',
        'back_to_home': 'Retour à l\'accueil',
        'see_all': 'Voir tout',
        'load_more': 'Charger plus',
        'slide_image': 'Image de la diapositive',
        'slide_title': 'Titre (optionnel)',
        'slide_subtitle': 'Sous-titre (optionnel)',
        'button_text': 'Texte du bouton',
        'button_link_type': 'Type de lien du bouton',
        'select_product': 'Sélectionner un produit',
        'download_url': 'URL de téléchargement',
        'custom_url': 'URL personnalisée',
        'none': 'Aucun (sans bouton)',
        'add_slide_title': 'Ajouter une diapositive',
        'edit_slide_title': 'Modifier la diapositive',
        'save_changes': 'Enregistrer les modifications',
        'slide_added': 'Diapositive ajoutée avec succès !',
        'slide_updated': 'Diapositive mise à jour avec succès !',
        'slide_deleted': 'Diapositive supprimée',
        'no_slides': 'Aucune diapositive. Cliquez sur "Ajouter une diapositive" pour commencer.',
        'marquee_settings': 'Paramètres du marquee',
        'enable_marquee': 'Activer le marquee',
        'marquee_text': 'Texte du marquee (séparez les éléments par | )',
        'marquee_saved': 'Paramètres du marquee enregistrés !',
        'user_menu': 'Menu',
        'requests': 'Demandes',
        'referrals_title': 'Parrainages',
        'reset_password': 'Réinitialiser le mot de passe',
        'send_link': 'Envoyer le lien',
        'search_placeholder': 'Rechercher des produits...',
        'no_matching': 'Aucun résultat correspondant',
        'country_tunisia': '🇹🇳 Tunisie',
        'country_algeria': '🇩🇿 Algérie',
        'country_morocco': '🇲🇦 Maroc',
        'country_egypt': '🇪🇬 Égypte',
        'country_saudi': '🇸🇦 Arabie Saoudite',
        'country_uae': '🇦🇪 EAU',
        'country_other': '🌍 Autre',
        'lang_english': '🇬🇧 English',
        'lang_arabic': '🇸🇦 العربية',
        'lang_french': '🇫🇷 Français',
        'lang_italian': '🇮🇹 Italiano',
        'lang_german': '🇩🇪 Deutsch',
        'lang_spanish': '🇪🇸 Español',
        'lang_portuguese': '🇵🇹 Português'
    },
    
    // ===== اللغة الإيطالية (IT) =====
    it: {
        'app_name': 'ZI Store',
        'welcome_back': '👋 Bentornato',
        'login_subtitle': 'Accedi per accedere ai tuoi script',
        'login_with_google': 'Accedi con Google',
        'or': 'o',
        'email': 'Email',
        'password': 'Password',
        'forgot_password': 'Password dimenticata?',
        'login': 'Accedi',
        'no_account': 'Non hai un account?',
        'sign_up': 'Registrati',
        'create_account': '✨ Crea account',
        'register_subtitle': 'Unisciti a ZI Store oggi',
        'full_name': 'Nome completo',
        'confirm_password': 'Conferma password',
        'country': 'Paese',
        'language': 'Lingua',
        'referral_code': 'Codice referral',
        'agree_terms': 'Accetto i Termini e Condizioni',
        'already_have_account': 'Hai già un account?',
        'search_products': '🔍 Cerca prodotti...',
        'notifications': 'Notifiche',
        'wishlist': 'Preferiti',
        'cart': 'Carrello',
        'profile': 'Profilo',
        'logout': 'Esci',
        'admin_panel': 'Pannello Admin',
        'all_scripts': 'Tutti gli script',
        'all': 'Tutti',
        'free': 'Gratuito',
        'vip': 'VIP',
        'browse': 'Sfoglia',
        'recommended': 'Consigliato per te',
        'no_products': 'Nessun prodotto',
        'no_results': 'Nessun risultato',
        'total': 'Totale',
        'favorites': 'Preferiti',
        'instant': 'Istantaneo',
        'secure': 'Sicuro',
        'support': 'Supporto 24/7',
        'unavailable': 'Non disponibile',
        'coming_soon': 'Prossimamente',
        'add_to_cart': 'Aggiungi al carrello',
        'download': 'Scarica',
        'details': 'Dettagli',
        'share': 'Condividi',
        'features': 'Caratteristiche',
        'verified': '✅ PRODOTTO 100% VERIFICATO',
        'price': 'Prezzo',
        'original_price': 'Prezzo originale',
        'cart_empty': 'Il carrello è vuoto',
        'start_shopping': 'Inizia a fare acquisti',
        'subtotal': 'Subtotale',
        'total': 'Totale',
        'checkout': 'Checkout',
        'clear_cart': 'Svuota carrello',
        'view_cart': 'Vedi carrello',
        'rp_points': 'Punti fedeltà',
        'use_rp': 'Usa RP',
        'promo_code': 'Codice promozionale',
        'apply': 'Applica',
        'discount': 'Sconto',
        'payment': 'Pagamento',
        'payment_method': 'Metodo di pagamento',
        'litecoin': 'Litecoin',
        'usdt': 'USDT',
        'telegram': 'Telegram',
        'binance': 'Binance',
        'exchange_rate': 'Tasso di cambio',
        'continue': 'Continua',
        'confirm_payment': 'Conferma pagamento',
        'back': 'Indietro',
        'amount': 'Importo',
        'copy_address': 'Copia indirizzo',
        'transaction_hash': 'Hash transazione',
        'paste_hash': 'Incolla l\'hash della transazione...',
        'contact_telegram': 'Contatta via Telegram',
        'edit_profile': 'Modifica profilo',
        'name': 'Nome',
        'telegram_username': 'Nome utente Telegram',
        'country_label': 'Paese',
        'language_label': 'Lingua',
        'save': 'Salva',
        'cancel': 'Annulla',
        'password_security': 'Password e sicurezza',
        'current_password': 'Password attuale',
        'new_password': 'Nuova password',
        'confirm_new_password': 'Conferma nuova password',
        'change_password': 'Cambia password',
        'send_reset_link': 'Invia link di reset',
        'telegram_notifications': 'Notifiche Telegram',
        'status': 'Stato',
        'linked': '✅ Collegato',
        'unlinked': '❌ Non collegato',
        'bind_chat_id': 'ID chat collegato',
        'bot': 'Bot',
        'link_bot': 'Collega bot',
        'test': 'Test',
        'check': 'Verifica',
        'unlink': 'Scollega',
        'connected_to': 'Collegato a',
        'start_bot': 'Avvia bot',
        'order_history': 'Cronologia ordini',
        'no_orders': 'Nessun ordine',
        'pending': 'In attesa',
        'confirmed': 'Confermato',
        'rejected': 'Rifiutato',
        'order_id': 'ID ordine',
        'order_date': 'Data ordine',
        'items': 'Articoli',
        'actions': 'Azioni',
        'delete': 'Elimina',
        'clear_history': 'Cancella cronologia',
        'notifications_title': 'Notifiche',
        'mark_all_read': 'Segna tutti come letti',
        'clear_all': 'Cancella tutto',
        'no_notifications': 'Nessuna notifica',
        'new': 'Nuovo',
        'activate_script': 'Attiva script',
        'enter_licence': 'Inserisci il codice licenza',
        'activate': 'Attiva',
        'my_licences': 'Le mie licenze',
        'no_licences': 'Nessuna licenza attiva',
        'expired': 'Scaduto',
        'active_until': 'Attivo fino al',
        'copy_code': 'Copia codice',
        'my_requests': 'Le mie richieste',
        'new_request': 'Nuova richiesta',
        'game_name': 'Nome gioco',
        'play_store_link': 'Link Play Store',
        'features_needed': 'Funzionalità desiderate',
        'budget': 'Budget',
        'submit_request': 'Invia richiesta',
        'refer_earn': 'Referral e guadagna',
        'referral_code_label': 'Il tuo codice referral',
        'referrals': 'Referral',
        'earned': 'Guadagnato',
        'referral_activity': 'Attività referral',
        'no_referrals': 'Nessun referral ancora',
        'share_code': 'Condividi il tuo link per iniziare a guadagnare',
        'steps': 'Passaggi',
        'step1': 'Condividi il tuo codice referral',
        'step2': 'Creano un account con il tuo codice',
        'step3': 'Guadagna ricompense (10% del loro primo ordine)',
        'joined': 'Iscritto',
        'dashboard': 'Dashboard',
        'orders': 'Ordini',
        'products': 'Prodotti',
        'users': 'Utenti',
        'downloads': 'Download',
        'statistics': 'Statistiche',
        'logs': 'Log',
        'slider': 'Slider',
        'licences': 'Licenze',
        'marquee': 'Marquee',
        'payments': 'Pagamenti',
        'total_orders': 'Totale ordini',
        'total_revenue': 'Entrate totali',
        'net_revenue': 'Entrate nette (10%)',
        'refresh': 'Aggiorna',
        'add_product': 'Aggiungi prodotto',
        'manage_featured': 'Gestisci in vetrina',
        'add_download': 'Aggiungi download',
        'send_notification': 'Invia notifica',
        'add_slide': 'Aggiungi slide',
        'create_licence': 'Crea licenza',
        'slider_settings': 'Impostazioni slider',
        'enable_slider': 'Attiva slider',
        'disabled': 'Disattivato',
        'rotation_interval': 'Intervallo rotazione (secondi)',
        'save_settings': 'Salva impostazioni',
        'loading': 'Caricamento...',
        'success': 'Successo',
        'error': 'Errore',
        'warning': 'Attenzione',
        'info': 'Info',
        'close': 'Chiudi',
        'search': 'Cerca',
        'edit': 'Modifica',
        'view': 'Vedi',
        'ban': 'Banna',
        'unban': 'Debanna',
        'delete_account': 'Elimina account',
        'confirm': 'Conferma',
        'cancel_action': 'Annulla',
        'yes': 'Sì',
        'no': 'No',
        'ok': 'OK',
        'back_to_home': 'Torna alla home',
        'see_all': 'Vedi tutti',
        'load_more': 'Carica altro',
        'slide_image': 'Immagine slide',
        'slide_title': 'Titolo (opzionale)',
        'slide_subtitle': 'Sottotitolo (opzionale)',
        'button_text': 'Testo bottone',
        'button_link_type': 'Tipo link bottone',
        'select_product': 'Seleziona prodotto',
        'download_url': 'URL download',
        'custom_url': 'URL personalizzato',
        'none': 'Nessuno (senza bottone)',
        'add_slide_title': 'Aggiungi nuova slide',
        'edit_slide_title': 'Modifica slide',
        'save_changes': 'Salva modifiche',
        'slide_added': 'Slide aggiunta con successo!',
        'slide_updated': 'Slide aggiornata con successo!',
        'slide_deleted': 'Slide eliminata',
        'no_slides': 'Nessuna slide. Clicca "Aggiungi slide" per iniziare.',
        'marquee_settings': 'Impostazioni marquee',
        'enable_marquee': 'Attiva marquee',
        'marquee_text': 'Testo marquee (separare gli elementi con | )',
        'marquee_saved': 'Impostazioni marquee salvate!',
        'user_menu': 'Menu',
        'requests': 'Richieste',
        'referrals_title': 'Referral',
        'reset_password': 'Reimposta password',
        'send_link': 'Invia link',
        'search_placeholder': 'Cerca prodotti...',
        'no_matching': 'Nessun risultato corrispondente',
        'country_tunisia': '🇹🇳 Tunisia',
        'country_algeria': '🇩🇿 Algeria',
        'country_morocco': '🇲🇦 Marocco',
        'country_egypt': '🇪🇬 Egitto',
        'country_saudi': '🇸🇦 Arabia Saudita',
        'country_uae': '🇦🇪 UAE',
        'country_other': '🌍 Altro',
        'lang_english': '🇬🇧 English',
        'lang_arabic': '🇸🇦 العربية',
        'lang_french': '🇫🇷 Français',
        'lang_italian': '🇮🇹 Italiano',
        'lang_german': '🇩🇪 Deutsch',
        'lang_spanish': '🇪🇸 Español',
        'lang_portuguese': '🇵🇹 Português'
    }
};

// ============================================================
// دوال الترجمة
// ============================================================

// اللغة الحالية
let currentLanguage = localStorage.getItem('zi_language') || 'en';

// دالة الترجمة
function t(key) {
    const lang = translations[currentLanguage] || translations['en'];
    return lang[key] || key;
}

// دالة تغيير اللغة
function setLanguage(lang) {
    if (translations[lang]) {
        currentLanguage = lang;
        localStorage.setItem('zi_language', lang);
        updateUILanguage();
        return true;
    }
    return false;
}

// دالة تحديث واجهة المستخدم
function updateUILanguage() {
    // تحديث جميع العناصر التي تحمل data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translation = t(key);
        if (translation) {
            // إذا كان العنصر input أو placeholder
            if (el.tagName === 'INPUT' && el.hasAttribute('placeholder')) {
                el.setAttribute('placeholder', translation);
            } else {
                el.textContent = translation;
            }
        }
    });

    // تحديث placeholder للبحث
    const searchInput = document.getElementById('liveSearchInput');
    if (searchInput) {
        searchInput.setAttribute('placeholder', t('search_products'));
    }

    // تحديث زر الترجمة في القائمة
    const langBtn = document.querySelector('.language-selector');
    if (langBtn) {
        const flagMap = {
            'ar': '🇸🇦',
            'en': '🇬🇧',
            'fr': '🇫🇷',
            'it': '🇮🇹',
            'de': '🇩🇪',
            'es': '🇪🇸',
            'pt': '🇵🇹'
        };
        langBtn.innerHTML = `${flagMap[currentLanguage] || '🌍'} ${currentLanguage.toUpperCase()}`;
    }

    // تحديث زر تبديل اللغة في القائمة الجانبية
    document.querySelectorAll('.lang-option').forEach(el => {
        el.classList.toggle('active', el.dataset.lang === currentLanguage);
    });

    console.log(`✅ Language updated to: ${currentLanguage}`);
}

// دالة عرض قائمة اللغات
function showLanguageMenu() {
    const menu = document.getElementById('languageMenu');
    if (menu) {
        menu.classList.toggle('open');
    }
}

// دالة إغلاق قائمة اللغات
function closeLanguageMenu() {
    const menu = document.getElementById('languageMenu');
    if (menu) {
        menu.classList.remove('open');
    }
}

// ============================================================
// تهيئة نظام الترجمة
// ============================================================

// تحميل اللغة المحفوظة
document.addEventListener('DOMContentLoaded', function() {
    // تحديث الواجهة
    updateUILanguage();

    // إضافة مستمع للنقر خارج القائمة
    document.addEventListener('click', function(e) {
        const menu = document.getElementById('languageMenu');
        const btn = document.querySelector('.language-selector');
        if (menu && btn && !menu.contains(e.target) && !btn.contains(e.target)) {
            closeLanguageMenu();
        }
    });
});

// تصدير الدوال للاستخدام العام
window.t = t;
window.setLanguage = setLanguage;
window.updateUILanguage = updateUILanguage;
window.showLanguageMenu = showLanguageMenu;
window.closeLanguageMenu = closeLanguageMenu;
window.currentLanguage = currentLanguage;
